api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "463412e20495250721be46dbab5b82a9751d64acd40208083a911f7ab943dd61"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "5a369ab8e3c36e9b31836c2f478bb5bb046fb65a8bc7fb8421929d381b6bd3a2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.84-any-stack-463412e2.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "0c5b058cee30c05370354bd9f976c496820dab95eaee5b11975a443704f2dd6f"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "0e89c6eecbd89d524be8654c5566ea4aad5d17f1f594a44ebc05a33ce546c231"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.93-any-stack-0c5b058c.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "e64ffd3c46a382b3075ca4525b042435cc4db7758006a1d24f2f10587c5d6ae5"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.52.tar.gz"
    source_sha256 = "7a778f9d412a61e59a0dfb072c4a3a5f1502be77b7042f5dcbb8b69409ae602f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.52-any-stack-e64ffd3c.tgz"
    version = "0.0.52"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "b4020fd4673a19ac9878a9634b09170d557e2f2bd95ab5aeb78cba69688a0a23"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.104.tar.gz"
    source_sha256 = "5b2573c890b27a5d814d5f52dd1794ce330547fd59ac69053bce546a97000966"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.104-cflinuxfs3-b4020fd4.tgz"
    version = "0.0.104"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "c34ef34c02cea01660e0b9ae48f1d080ef5933d23e10eef80cbb406339484ce3"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "9b1dadbe7dbca44c1e185efebd3a535f1c861ecd43be620551103fe91b517a1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.82-any-stack-c34ef34c.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.52"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.104"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.52"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.93"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"
