api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "d1ccd8a1d574666694451bd6f4c79218f59f8b9b50290185ccfd1e9a6a2ac3ba"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "c8889aef2be48e3a6d218e685e68aff9ea3fdb7c6c9da1464e6d98d09bfa6860"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.80-any-stack-d1ccd8a1.tgz"
    version = "0.0.80"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "c5e87cc610d47debe14682819f834332c377f6ee4bd0f4aea594ec906c44eab3"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "8ee66a7e72b970a2d8b3206a7214c5a56a8de8340be45d458de5189b1e92ac8e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.90-any-stack-c5e87cc6.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "c1038a3e4b29bc0279f3f556af8a54a10ee45409c1a7f293dd7d08a66e348778"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "b4a59e1695a65bc128bba4dd835f6a930f81b3e5ba6fc028fd3f040b8a56bc03"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.89-any-stack-c1038a3e.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "a1c59baa262adea41e728b167e6c3157725c2a62cd3695c607ddb32862367729"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.80.tar.gz"
    source_sha256 = "6b0a9142aa86aebb14f2905b2508394302c591b449af4fbce4b5986c317c6803"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.80-any-stack-a1c59baa.tgz"
    version = "0.0.80"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.80"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.80"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.80"
