api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "85dc8e024f3e588d3f57a9a01c700e2d44ec8fbf366c2bdb11a1546f16bec063"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "a4579924826d5c46e341ae68d39aa556997e32f294bd5796e6e9819cd00509ea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.64-any-stack-85dc8e02.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "071ace53a12808b712939dab73b6748254ab6e51012deb1c91e5a2b0cc44f988"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.69.tar.gz"
    source_sha256 = "072cb68bdd8d8f4193f766c7ca29af32db3bb668f1d4b684f5cfadae3d98b43a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.69-any-stack-071ace53.tgz"
    version = "0.0.69"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "67caf63c664d339821b5766f9eb7b79b06d78d75eebb1373e7de5b0f1339ed25"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "46190c4a68c8a88b5d3a76008706619727b9f55d3691909d65cc590e71a540a4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.71-any-stack-67caf63c.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "da7ddc088af9f7a41a109713a9e0350a24d43d64d4db2416baed1203d4129f03"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "5d96e04bdeb0a48557993475c638551e60118dd9fb330652c228789c1341000e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.70-any-stack-da7ddc08.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.71"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.64"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.71"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.69"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.70"
