api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "dfd95b8936aa092eb0d71159bd0913ed8a636acd8e1b5d562675ca8c9a865f3e"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "4a039f0246e5ab6e68deed3efd303bd2c18a299a46288310b7cae5a2e235fbdb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.97-any-stack-dfd95b89.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "aef0ebc3788313e07b4693c9d08bdfba413c36c5ff32b779772a97022f5f3b07"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "e60eb7949c617f43faf5b10421627f00cac7a4d668df2388697f8e757a18ef6f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.103-any-stack-aef0ebc3.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "5193b6a45191f226458b3b6edf23b909904f5d7ee7b490c5daf682fa3d0db9e0"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "36c821e66fb2a06eda3ca6efaeec8bd7354f1d8cba57a496805556e4d381d3c8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.58-any-stack-5193b6a4.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "c7da4a9762847a302455cbd5ae6e5a5fc42d9560d6d3d217a54073e1fd77ef9f"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.124.tar.gz"
    source_sha256 = "b635e6844f1812a274a8bcd77452d289a9dfed7631a56e4cdacba28fab7d06fc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.124-cflinuxfs3-c7da4a97.tgz"
    version = "0.0.124"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "e680dbcbf3fddb9ac6aec31e4b6b55184c40e0d9f462ae2b7afa7bd9437e8de5"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "a2db1040aa4f926a0b2084070cf3d718a129e50c91be5cdd0c0745e5544e1d39"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.83-any-stack-e680dbcb.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.103"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.124"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.58"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.83"
