api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "bd3d1de438ec13f55c26505d9cfc148bf18ce3621932a50ec907c3fa911389b8"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "e38948f5ec3f8e6acfee63f18b8feeea37facd795f00ad5195de264796ae2aeb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.90-any-stack-bd3d1de4.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "c7921fd66a299422f0c6c440fbab9d34600f9a02ae4d8fcd52d2ef6ee4180379"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.97.tar.gz"
    source_sha256 = "0c0e59a2fa98f7cbbce21587fb5437132576b99b25e4c6e9659c54cd40adb08c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.97-any-stack-c7921fd6.tgz"
    version = "0.0.97"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "2c8a5ba034d28c615a61b7850dc3e09de5e51bb719017998ee8089859ed8f5ec"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "19d826e1d6458c23c0a45705536a478d9ba2cf392592e642d8b1675e5f1c061d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.56-any-stack-2c8a5ba0.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "7d09c91e4bd1f28442fb757ac250b0bb929f04d0db274fdc3f9dceadc5cc9ea0"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "38571c227edc62702201da7b9a997278b6a1a8c56e2b493893dd510a2c144386"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.110-cflinuxfs3-7d09c91e.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "c34ef34c02cea01660e0b9ae48f1d080ef5933d23e10eef80cbb406339484ce3"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "9b1dadbe7dbca44c1e185efebd3a535f1c861ecd43be620551103fe91b517a1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.82-any-stack-c34ef34c.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.56"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.110"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.56"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.97"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"
