api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "a7dd88bc25e45024e8ae01f1d8d88a08144541b9c1113d54716f36e230ab5ab5"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "f2b0bec6c9788f1a777e2269315efc55607726faee9bb758f81b7a64b5bf0848"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.51-any-stack-a7dd88bc.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "c08f0f36b847042f58ab3930e405841da65b44152f72a44d61e6a064c41bfe90"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "b4f57fc13295ca122509cd78854a632dcffd4942fbb27b5416e2433ddabfec01"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.55-any-stack-c08f0f36.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "c08f0f36b847042f58ab3930e405841da65b44152f72a44d61e6a064c41bfe90"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "b4f57fc13295ca122509cd78854a632dcffd4942fbb27b5416e2433ddabfec01"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.55-any-stack-c08f0f36.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "04d5eb413ea77244c207f531d198a377a9761b2150ce29742847bb45f3fea0c7"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "5700bbb30c47f3c7773f29b209568a7dae7541472d5e071bed7e475314b7c98b"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.55-any-stack-04d5eb41.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "0e9fd968da7eadb4a09c77e37db81b4c7898013ddd16631bf4846f238366c908"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "a2277d94a9a310d81642ee6bae6d24a4a66dfd562c5b66505e62ef93945bf58a"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.59-any-stack-0e9fd968.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "0e9fd968da7eadb4a09c77e37db81b4c7898013ddd16631bf4846f238366c908"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "a2277d94a9a310d81642ee6bae6d24a4a66dfd562c5b66505e62ef93945bf58a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.59-any-stack-0e9fd968.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "e28be5df46b949ca5452a9b731f8204799f688f6aec6743a56c09c9270d4c797"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.35.tar.gz"
    source_sha256 = "1f7fec7566031e62e2c48f46879e3882dcb05f7ce94a8d4fa954310f4af6513c"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.35-any-stack-e28be5df.tgz"
    version = "0.0.35"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "d2f99b111cd7e0be6521d305c46f603eebd381959a7b5ad06df4263b2f2bd3f6"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "7c856c0cc0142b7d996d09983899575d6e9e634901fae19462da28e2d6ff3aa3"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.37-any-stack-d2f99b11.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "d2f99b111cd7e0be6521d305c46f603eebd381959a7b5ad06df4263b2f2bd3f6"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.37.tar.gz"
    source_sha256 = "7c856c0cc0142b7d996d09983899575d6e9e634901fae19462da28e2d6ff3aa3"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.37-any-stack-d2f99b11.tgz"
    version = "0.0.37"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "f053c49fcebd5de0adab4f7a50c6c48df1cbba0a0ef1c839cfc83dc38a7c5e68"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "4e77c325c80495b09844044b1aa6fbf42306db1b901fcba8f87b24a018f0a5ef"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.58-any-stack-f053c49f.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "bc17ac53292c1ade16fb6e82c9117389e920a81a900eb1fcaebae8d850f24646"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "4eba1d1bb30b959d44f8b6d23ff1112b10de85b624d5147501e0279b7d4d6239"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.60-any-stack-bc17ac53.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "bc17ac53292c1ade16fb6e82c9117389e920a81a900eb1fcaebae8d850f24646"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "4eba1d1bb30b959d44f8b6d23ff1112b10de85b624d5147501e0279b7d4d6239"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.60-any-stack-bc17ac53.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "75679a316c658988c8369b794fc1a541a6ba7381c3af15de018973283da69c82"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "b4e6cfa1d6a8a26341eb6dd00e82cc23544f3f4f3590cacf905313070557601e"
    stacks = ["org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.55-any-stack-75679a31.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "7e98cfd7a1afb57216a5a429f0ddbdaedd7d42e50e96b1be779f87a15c6df4b8"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "a51d732a427390798dee720a985b00dcc849c1a8659679aa7de2ae8102e0cf1c"
    stacks = ["io.buildpacks.stacks.bionic"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.59-any-stack-7e98cfd7.tgz"
    version = "0.0.59"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "7e98cfd7a1afb57216a5a429f0ddbdaedd7d42e50e96b1be779f87a15c6df4b8"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.59.tar.gz"
    source_sha256 = "a51d732a427390798dee720a985b00dcc849c1a8659679aa7de2ae8102e0cf1c"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.59-any-stack-7e98cfd7.tgz"
    version = "0.0.59"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.60"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.37"

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.55"

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.59"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.60"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.37"

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.59"

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.59"
