api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "62a68187f50b3239d2233cbc9c807d3ee371d940355596f86453519014340218"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.66.tar.gz"
    source_sha256 = "7c72f80b6f407256c4e09e26b23860172fa5579e6aa95eb1808a6a962a8664b4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.66-any-stack-62a68187.tgz"
    version = "0.0.66"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "0673e5dd4d7acba80becb853b620e3ced18895ca495cca05481d3dac39e49256"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.71.tar.gz"
    source_sha256 = "6eb421f024bbdcaa63f94fab6f86bf11410f4c89cec44700edb85ee749b0701a"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.71-any-stack-0673e5dd.tgz"
    version = "0.0.71"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "421d36cf2851a8f26bb3231999e747e8da4feafdab19564794d203397140ddab"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.75.tar.gz"
    source_sha256 = "5df60a66b97e6a018a6edbe9aa285a8fc9190092811ae9f0b69eabcb11a060bf"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.75-any-stack-421d36cf.tgz"
    version = "0.0.75"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "da7ddc088af9f7a41a109713a9e0350a24d43d64d4db2416baed1203d4129f03"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "5d96e04bdeb0a48557993475c638551e60118dd9fb330652c228789c1341000e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.70-any-stack-da7ddc08.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.75"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.66"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.75"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.71"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.70"
