api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "016202792fdabcd69462d414e5694a01ca515bbe66a780fd888b50a9c5d03945"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "4168a76be5eadd40671bbddbef93903211f33d7d7fea41f24f315aee63c42302"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.77-any-stack-01620279.tgz"
    version = "0.0.77"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "aeefaf3fcdfc3a05d2b60e65fb4afe15fdfd730f8a6c4e04e74fdafd819913de"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "ac0760111cd12fd249938d1296b0c4e9872fe5bc3b7578231d1c0e34b26fb6a6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.84-any-stack-aeefaf3f.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "439c6c1cc4a4aac4f64abaa1e12f0cd1f8b11cc238d811b66df3e613335d799f"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.85.tar.gz"
    source_sha256 = "f6cdd082cc2fccf1d5f0ef3357155cfa609c2abe859ba79290a47d90fedf8d15"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.85-any-stack-439c6c1c.tgz"
    version = "0.0.85"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "d0b9df18e126369e2650de99a2a9e11ffafb01aef9a9c2f30dbad4c7750fde53"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.77.tar.gz"
    source_sha256 = "b4cb8aed33e5ed211bd2935dee0b313fca932dfe08c2ba43773f6e1df6b96ca7"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.77-any-stack-d0b9df18.tgz"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.85"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.77"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.77"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.85"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.77"
