api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "463412e20495250721be46dbab5b82a9751d64acd40208083a911f7ab943dd61"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.84.tar.gz"
    source_sha256 = "5a369ab8e3c36e9b31836c2f478bb5bb046fb65a8bc7fb8421929d381b6bd3a2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.84-any-stack-463412e2.tgz"
    version = "0.0.84"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "0c5b058cee30c05370354bd9f976c496820dab95eaee5b11975a443704f2dd6f"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "0e89c6eecbd89d524be8654c5566ea4aad5d17f1f594a44ebc05a33ce546c231"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.93-any-stack-0c5b058c.tgz"
    version = "0.0.93"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "fe1d0f0628b89cbf6748c1e65ea02523b98ae79cfa453b298f404af126b19b61"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "6c6b58406e589a786a5487e406c73de83a527853b91c2e1fb643ffbc8ef64d81"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.51-any-stack-fe1d0f06.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "70c3d91488208511025e3981393cee6a0753664af2eb9dd2a9d9cf3b54946c35"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "4fc1d1f7509a66af8ae9bdcef5b218acde1afebcc6c7fde5fd37dcc562203873"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.102-cflinuxfs3-70c3d914.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "c34ef34c02cea01660e0b9ae48f1d080ef5933d23e10eef80cbb406339484ce3"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "9b1dadbe7dbca44c1e185efebd3a535f1c861ecd43be620551103fe91b517a1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.82-any-stack-c34ef34c.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.84"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.102"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.93"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"
