api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "7adbc3e6284d99b5353c9b31f8805f3ddb249d0927b327926008ab1392d2645c"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "2afd59925713f0dc257c6b2526b541e959838c7d45d16ec795871f037b17a1dc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.70-any-stack-7adbc3e6.tgz"
    version = "0.0.70"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "356ce54c55b6f6ea928befb1c7abf093c4255897eeeaefde45994bdfaf423b94"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.76.tar.gz"
    source_sha256 = "e83df0e310fb01cf79cd4277bebfa8d7a7bf1090f596f83e3313147bf491097d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.76-any-stack-356ce54c.tgz"
    version = "0.0.76"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "3ea926d0e2d533fa580feccd3b60bc8b5577297c6c77d7be48595caf4609c5bb"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "f6736d5889eeb99e3c72a1252b4948d20e93587807ba7c3819c758b69a943480"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.79-any-stack-3ea926d0.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "07094e3fb9b0b3a9a14374c5b28bac4389f4c84885a3edf59db36a5756167164"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.72.tar.gz"
    source_sha256 = "c799505920ae8c5e3c2260bb2b10307a84054ca5e3d9284fc72d15d11af42303"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.72-any-stack-07094e3f.tgz"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.70"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.72"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.79"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.76"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.72"
