api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "bd3d1de438ec13f55c26505d9cfc148bf18ce3621932a50ec907c3fa911389b8"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "e38948f5ec3f8e6acfee63f18b8feeea37facd795f00ad5195de264796ae2aeb"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.90-any-stack-bd3d1de4.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "7575050928089f7eef270e8b9d6007d267ccbbde23953180b0a924d66822e4a4"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "8642cf67ebc1e15315382a580d27fec5abac68b8b64dde0919a8c08b35c78611"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.96-any-stack-75750509.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "124505029afb821bd3dcb5b5dfbfadd410310c417fe32f3ba4c5f3274352d669"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.55.tar.gz"
    source_sha256 = "6992adef1ea95ed2ba11d6cc0b5c445da1a08fa4251821c71c3be2dfc3bad15c"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.55-any-stack-12450502.tgz"
    version = "0.0.55"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "b8886258c0e8906c554e135dcf2069cd8d7e2ac3999e35e222a96d31c66cd816"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.108.tar.gz"
    source_sha256 = "a4cc9467d4f6aa4d12706a0f95456cb5ab8c2d3a28ed6b833f39420207757ee6"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.108-cflinuxfs3-b8886258.tgz"
    version = "0.0.108"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "c34ef34c02cea01660e0b9ae48f1d080ef5933d23e10eef80cbb406339484ce3"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "9b1dadbe7dbca44c1e185efebd3a535f1c861ecd43be620551103fe91b517a1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.82-any-stack-c34ef34c.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.108"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.55"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.108"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.55"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.96"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.82"
