api = "0.2"

[buildpack]
id = "org.cloudfoundry.php"
name = "PHP Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.httpd"
sha256 = "042e1d3e7222742ec477a927aceb2c1f754f06b34d5740c2508e1938f418a09e"
source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.35.tar.gz"
source_sha256 = "9c4e94daaa849c6198f9fb10ceb4d84d21a4c1972dfa6972108e21cdfc3696ca"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.35-any-stack-042e1d3e.tgz"
version = "0.0.35"

[[metadata.dependencies]]
id = "org.cloudfoundry.nginx"
sha256 = "005c39bf0b80852384c55567cfef65bef3fdaa1ff888e95ef538f6916bc321c1"
source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.38.tar.gz"
source_sha256 = "f6452620de28ec1a13197761b4888b0e6eb8afaa02aad77d5e897fd2573248a5"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.38-any-stack-005c39bf.tgz"
version = "0.0.38"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-composer"
sha256 = "4a032ebecd766375939417e42c08f8180f2143db54a9b1fa83bf39a3ce376984"
source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.23.tar.gz"
source_sha256 = "37526ad40f94b539e3f47f1c745710e9a8c79a5a897a3a6067f1ab7d50797ea7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.23-any-stack-4a032ebe.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-dist"
sha256 = "df1b6d5dd38707f783ec0108ced69feea1e4894aace7c801ad0609105a771c36"
source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.44.tar.gz"
source_sha256 = "ba0f6052a982beebea2f3a128b85a820f77f28bdad5a789ebff848528f67f929"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.44-any-stack-df1b6d5d.tgz"
version = "0.0.44"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-web"
sha256 = "2f49106b36eeec6d6fe2895ca56292e706e2ba2557341b31f6063aa85c7d4f10"
source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "941a2eb2f77375fe070b09d0b17ffd269aa1c4bf92e2f4c06beff38e1fff8c98"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.37-any-stack-2f49106b.tgz"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.php-dist"
version = "0.0.44"

[[order.group]]
id = "org.cloudfoundry.php-composer"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.httpd"
optional = true
version = "0.0.35"

[[order.group]]
id = "org.cloudfoundry.php-web"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.php-dist"
version = "0.0.44"

[[order.group]]
id = "org.cloudfoundry.php-composer"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.nginx"
optional = true
version = "0.0.38"

[[order.group]]
id = "org.cloudfoundry.php-web"
version = "0.0.37"
