api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "958cb968f9f0968a4880f7e611ccec9eaa3ccd226b992d84b2f4fdd93d1a6f4a"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "047a117bfefb1d11436b99bb783cc2f7b5424c0d4d93617123a24e9c8d2b1358"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.73-any-stack-958cb968.tgz"
    version = "0.0.73"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "2bc3b46d320f0ff5ff04d526611d151cbd8e61a786133487d9a6362ead009f84"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.79.tar.gz"
    source_sha256 = "f41503d9c5baf63d1629cf1644888c51596f81a22f2369483dc1cb4b9aebc325"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.79-any-stack-2bc3b46d.tgz"
    version = "0.0.79"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "6b8ca342816476515fb55e4fd92383457735a9a70ce134690d24069d18b3fede"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "c068a32221c43cd1a54859297fed7201f1e7b28c83acc87ddab21bf36a88c8cd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.82-any-stack-6b8ca342.tgz"
    version = "0.0.82"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "849c2624539ed5243ea54bc6340c80f2ef7cddf305f782a847da5d36d9976e53"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.73.tar.gz"
    source_sha256 = "c543865e01a532d0c0e1c5185ec37d5173bc8eed8228395abc69d13187bf4465"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.73-any-stack-849c2624.tgz"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.82"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.73"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.73"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.82"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.79"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.73"
