api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "29bdeb1469c99912fc02690ca99d92c0514c3e1447da258f901acd95768ec75b"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "e3389d38b07caca8b221ea8c45e4464fa522fd4c85e0e3e79016fe664ebc6ede"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.62-any-stack-29bdeb14.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "058a12a1d6d4b0c4504d85bd70db27ef3a955effa8207d4c296c51723a405825"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "9ddda5196d37f885fddcaee9605ec6814ffc68d7a78396c5307aa720437f6e08"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.67-any-stack-058a12a1.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "3bf18717bf568709efb3517a5ccb9170e019d7d1979e6c7383e0bacd2780a0cc"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.44.tar.gz"
    source_sha256 = "ecbca90cdbd34d9b58f88d33f3637f9e2caff16e4d135df737c26e98e8851960"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.44-any-stack-3bf18717.tgz"
    version = "0.0.44"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "03fe943c25e44e7fa2248cc1209bc0c6760b1a3f31f18f9b7f4c4d6d68e4747d"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.64.tar.gz"
    source_sha256 = "c846c4bff768ea674d78b2f22baba64cf1028045fb0b95eacc2a622c96b3c088"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.64-any-stack-03fe943c.tgz"
    version = "0.0.64"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "d53390e2ec9e287c71d8d07c3732f2a1e8d7ca9a493eea6c1441f2ba2f1e9cd1"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "d232ad6abc1a8bf2c1419b88f0b95caf6a7c9f5a1793da12fae05fceb7bba22b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.67-any-stack-d53390e2.tgz"
    version = "0.0.67"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.64"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.44"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.62"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.67"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.64"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.44"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.67"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.67"
