api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "a6bbaaf75ef08dbdac3b4386b705a924f14e8ea64a4cd734a155ee5ad7d4ce4d"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "894728d1a219872c3d5e52f1d202bfac79508b832173a83c86972a57b2b9a060"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.63-any-stack-a6bbaaf7.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "514b4dde6e29a3343dfec73d878b4d8b7e0717b4d1ee719ca4cbccc8c2bf9be4"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.68.tar.gz"
    source_sha256 = "1faa981dd1108c3437f4eaa39d782bd0f813693990608f1901ca41f70e563bf1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.68-any-stack-514b4dde.tgz"
    version = "0.0.68"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "abe1de785f0afeed53e603383eca5908f21c036e65de4aaf01cb89ca65a08d31"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.46.tar.gz"
    source_sha256 = "3403e019f3dd209abf87c4c3c38b81b26e3032f99ac6cca416009859b3347ff1"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.46-any-stack-abe1de78.tgz"
    version = "0.0.46"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "51cdc4af47fe3a1e85298e66d9392d26b975851201e6d2451d191026246692da"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.67.tar.gz"
    source_sha256 = "14cf9346d052cef626a1bf54f98a67bc806ce3f804c076a0504015fad4ba705e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.67-any-stack-51cdc4af.tgz"
    version = "0.0.67"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "da7ddc088af9f7a41a109713a9e0350a24d43d64d4db2416baed1203d4129f03"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.70.tar.gz"
    source_sha256 = "5d96e04bdeb0a48557993475c638551e60118dd9fb330652c228789c1341000e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.70-any-stack-da7ddc08.tgz"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.46"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.63"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.70"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.67"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.46"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.68"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.70"
