api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "85fee56ed259e0d55363740a0989ad294afe3ba709cd3d69ff31458358350bc3"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "b5e455bd1925da2f5a1da50e3174f3e836b1d3ee513450dc33b34732bdef2b15"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.81-any-stack-85fee56e.tgz"
    version = "0.0.81"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "c5e87cc610d47debe14682819f834332c377f6ee4bd0f4aea594ec906c44eab3"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "8ee66a7e72b970a2d8b3206a7214c5a56a8de8340be45d458de5189b1e92ac8e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.90-any-stack-c5e87cc6.tgz"
    version = "0.0.90"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "46faf90b8136e88bbe8ae710c1666f0e14104c1475ee1edd1c761d8e7b60cd64"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.47.tar.gz"
    source_sha256 = "780c3d8ea1651e048d74223205f22a2cb9d386fa54018daf90d99dcfca6e79b3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.47-any-stack-46faf90b.tgz"
    version = "0.0.47"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "c1038a3e4b29bc0279f3f556af8a54a10ee45409c1a7f293dd7d08a66e348778"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.89.tar.gz"
    source_sha256 = "b4a59e1695a65bc128bba4dd835f6a930f81b3e5ba6fc028fd3f040b8a56bc03"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.89-any-stack-c1038a3e.tgz"
    version = "0.0.89"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "7f55d52223eb623e7c650a452cd25e03797a890f87e50e48e691e81496f67678"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.81.tar.gz"
    source_sha256 = "83f88556e455ff8a84af040614d1c6c9fb2e627167e01ee0542d46750364214d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.81-any-stack-7f55d522.tgz"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.81"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.81"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.89"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.47"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.90"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.81"
