api = "0.2"

[buildpack]
id = "org.cloudfoundry.php"
name = "PHP Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.httpd"
sha256 = "a32119a97f8d285464bfeb959ff568d2b344c5483cb56be821c20d39b0f409da"
source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.34.tar.gz"
source_sha256 = "eefc9fcfe86617809de081becdc17dab8a31195ce3f7b28e60da4cc4c8622a0a"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.34-any-stack-a32119a9.tgz"
version = "0.0.34"

[[metadata.dependencies]]
id = "org.cloudfoundry.nginx"
sha256 = "7c1e596cda5d75128d134d95b3b98a32f2305055e827c547a2ef882b7429b906"
source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "2b26774ea5a70a9cb43a0f3396b46b8df55d245d4a405e16f28f1d034ccecc48"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.37-any-stack-7c1e596c.tgz"
version = "0.0.37"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-composer"
sha256 = "4a032ebecd766375939417e42c08f8180f2143db54a9b1fa83bf39a3ce376984"
source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.23.tar.gz"
source_sha256 = "37526ad40f94b539e3f47f1c745710e9a8c79a5a897a3a6067f1ab7d50797ea7"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.23-any-stack-4a032ebe.tgz"
version = "0.0.23"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-dist"
sha256 = "1b7b04df7280f7a43958d5ff480c610d4e314d3e9a307ed3798d022cb81ab65d"
source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.42.tar.gz"
source_sha256 = "4c7df1d72451ed47ded22e36ed603e2e6eb74360cceda1259254d3a95bf6a554"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.42-any-stack-1b7b04df.tgz"
version = "0.0.42"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-web"
sha256 = "2f49106b36eeec6d6fe2895ca56292e706e2ba2557341b31f6063aa85c7d4f10"
source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.37.tar.gz"
source_sha256 = "941a2eb2f77375fe070b09d0b17ffd269aa1c4bf92e2f4c06beff38e1fff8c98"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.tiny"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.37-any-stack-2f49106b.tgz"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.php-dist"
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.php-composer"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.httpd"
optional = true
version = "0.0.34"

[[order.group]]
id = "org.cloudfoundry.php-web"
version = "0.0.37"

[[order]]

[[order.group]]
id = "org.cloudfoundry.php-dist"
version = "0.0.42"

[[order.group]]
id = "org.cloudfoundry.php-composer"
optional = true
version = "0.0.23"

[[order.group]]
id = "org.cloudfoundry.nginx"
optional = true
version = "0.0.37"

[[order.group]]
id = "org.cloudfoundry.php-web"
version = "0.0.37"
