api = "0.2"

[buildpack]
  id = "org.cloudfoundry.php"
  name = "PHP Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "5a3a4830a9577387b1abcd8bd8123657e11e9ebb5fb2f7aac3f67eb315dbd1c0"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "ccd550033565d2c85b6322f374d9361a8c22c242106b913482fa2923553f6eac"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd_0.0.103_linux_noarch_any-stack_5a3a4830.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "1bd37c543c50e98ebd31109ba9aff9e2bdd3de2ead668d12a9407515921eb84f"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "722bb3386d56163270ba5afeaf85928e44a153f4502773e4c137a20d1e77f95f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx_0.0.107_linux_noarch_any-stack_1bd37c54.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "ed4d0c6462f41b8fec1d752f64ac9c4231b976060e8a5b2458a62c6fee333600"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.62.tar.gz"
    source_sha256 = "689dfe80168711d0dc216108c94351e9acdb2fed161f347d4dc33a5f0315515b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer_0.0.62_linux_noarch_any-stack_ed4d0c64.tgz"
    version = "0.0.62"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "a682a9ddf1d095dcc05c497fb639f0995becec38b79b5435376f20ef634ee563"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.132.tar.gz"
    source_sha256 = "6d3d49fc10f1ac4281de4951e984ad516cafd4654b9286fb835c4f485524db66"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist_0.0.132_linux_noarch_cflinuxfs3_a682a9dd.tgz"
    version = "0.0.132"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "22eee8f4f792400290181a47f1468aba07e935f1290f0a1b64e8dbb8af39844e"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.88.tar.gz"
    source_sha256 = "9f2434ba0ae5ec9e8412ef96ba354bc485643a53daa6b17101c0b71ca80c81d5"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web_0.0.88_linux_noarch_any-stack_22eee8f4.tgz"
    version = "0.0.88"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.103"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.107"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.132"

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.62"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.88"
