api = "0.2"

[buildpack]
id = "org.cloudfoundry.php"
name = "PHP Buildpack"
version = "{{.Version}}"

[metadata]
include_files = ["buildpack.toml"]

[[metadata.dependencies]]
id = "org.cloudfoundry.httpd"
sha256 = "d312122fee1707465e3b8420ce75c9a7905cb42291a4c2eebc72b5a49a6a5fca"
source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.47.tar.gz"
source_sha256 = "98ea006d7edeeae6fd77bebd0cbb67e0f5f14f9f8caae6f83e54ab9d9e4e774a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.47-any-stack-d312122f.tgz"
version = "0.0.47"

[[metadata.dependencies]]
id = "org.cloudfoundry.nginx"
sha256 = "1729733524c91f25c04ce6b07282391898dccbf74fe8004895504d0b1b6195fe"
source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.51.tar.gz"
source_sha256 = "56c85f1b6ff0a5131ba00ff7aac469fd01baba929b5406f7f1a220b2c965c583"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.51-any-stack-17297335.tgz"
version = "0.0.51"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-composer"
sha256 = "3d6f22464616ede4c399db411357eb9f40cf3b844636b71b34bc217a7b7fd5b7"
source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.29.tar.gz"
source_sha256 = "4afb2dbb9a8d63a4ba3a5be9f658c76d83ec5c8778286034438913cb67b43e8a"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.29-any-stack-3d6f2246.tgz"
version = "0.0.29"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-dist"
sha256 = "ade94fe982e3ba86dea9315c553e41ecae5b41af7e126b53cf6b489a35b6adc4"
source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.52.tar.gz"
source_sha256 = "98cb2ebf8e5d70a201aec8cfda5e79ba7b910f12cf66fc402d4e1853487e0fbb"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.52-any-stack-ade94fe9.tgz"
version = "0.0.52"

[[metadata.dependencies]]
id = "org.cloudfoundry.php-web"
sha256 = "954c9dc387552c507155f28630663a3c1dbd0fae5c1021661987f61e2d103d1f"
source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.50.tar.gz"
source_sha256 = "f9263a3bb67e2c95233e14257068c1ad7db1e05b739bd1e6c79cf1a27de99be0"
stacks = ["org.cloudfoundry.stacks.tiny","io.buildpacks.stacks.bionic","org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.50-any-stack-954c9dc3.tgz"
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.php-dist"
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.php-composer"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.httpd"
optional = true
version = "0.0.47"

[[order.group]]
id = "org.cloudfoundry.php-web"
version = "0.0.50"

[[order]]

[[order.group]]
id = "org.cloudfoundry.php-dist"
version = "0.0.52"

[[order.group]]
id = "org.cloudfoundry.php-composer"
optional = true
version = "0.0.29"

[[order.group]]
id = "org.cloudfoundry.nginx"
optional = true
version = "0.0.51"

[[order.group]]
id = "org.cloudfoundry.php-web"
version = "0.0.50"
