api = "0.2"

[buildpack]
  id = "org.cloudfoundry.shim.php"
  name = "PHP Shim Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/releases/download/v0.5.0/lifecycle-v0.5.0%2Blinux.x86-64.tgz"
    source_sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "b83c4fc2b6ca5f40f1ec42b5d759d25bacc7deea7528e6d0935e5bc0fe4d1ab6"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.96.tar.gz"
    source_sha256 = "d3ec0ba8e6405aff468804b46f66fd5546a02431a165b482d31861b2cc1b1cdc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.96-any-stack-b83c4fc2.tgz"
    version = "0.0.96"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "aef0ebc3788313e07b4693c9d08bdfba413c36c5ff32b779772a97022f5f3b07"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.103.tar.gz"
    source_sha256 = "e60eb7949c617f43faf5b10421627f00cac7a4d668df2388697f8e757a18ef6f"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.103-any-stack-aef0ebc3.tgz"
    version = "0.0.103"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-compat"
    sha256 = "f88d28aa7e2f687b37abc4eca85847d24052182448b44b27396c25483c1f338e"
    source = "https://github.com/cloudfoundry/php-compat-cnb/archive/v0.0.51.tar.gz"
    source_sha256 = "ed89180be71a3389bf8aa8e3d3bebdfccb80a2bad0d16b7f98b75443550badbe"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-compat/org.cloudfoundry.php-compat-0.0.51-any-stack-f88d28aa.tgz"
    version = "0.0.51"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "5193b6a45191f226458b3b6edf23b909904f5d7ee7b490c5daf682fa3d0db9e0"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.58.tar.gz"
    source_sha256 = "36c821e66fb2a06eda3ca6efaeec8bd7354f1d8cba57a496805556e4d381d3c8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.58-any-stack-5193b6a4.tgz"
    version = "0.0.58"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "c7da4a9762847a302455cbd5ae6e5a5fc42d9560d6d3d217a54073e1fd77ef9f"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.124.tar.gz"
    source_sha256 = "b635e6844f1812a274a8bcd77452d289a9dfed7631a56e4cdacba28fab7d06fc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.124-cflinuxfs3-c7da4a97.tgz"
    version = "0.0.124"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "e680dbcbf3fddb9ac6aec31e4b6b55184c40e0d9f462ae2b7afa7bd9437e8de5"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "a2db1040aa4f926a0b2084070cf3d718a129e50c91be5cdd0c0745e5544e1d39"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.83-any-stack-e680dbcb.tgz"
    version = "0.0.83"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.96"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.103"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.124"

  [[order.group]]
    id = "org.cloudfoundry.php-compat"
    version = "0.0.51"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.58"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.83"
