api = "0.2"

[buildpack]
  id = "org.cloudfoundry-test.shim.php"
  name = "PHP Shim Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    source = "https://github.com/buildpacks/lifecycle/releases/download/v0.7.2/lifecycle-v0.7.2%2Blinux.x86-64.tgz"
    source_sha256 = "5abc450423b9a13cf3e8f83623d30cd61081af293e85044a8d6d88e29548cc66"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.7.2-any-stack-5abc4504.tgz"
    version = "0.7.2"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-compat"
    sha256 = "298a48fb72d2106d809cd43106e247437cd9727277c3c7bab7c5f75a4d10bf9d"
    source = "https://github.com/cloudfoundry/php-compat-cnb/archive/v0.0.57.tar.gz"
    source_sha256 = "5eaed31da7f19cffe73f8df61213b3a66bd5b08a6f2f31cf23641226952f78fd"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-compat/org.cloudfoundry.php-compat_0.0.57_linux_noarch_any-stack_298a48fb.tgz"
    version = "0.0.57"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "083c4563d8acb9aaa5fb3ddfce3298f6c538c41be2eea5bc896a64960b9cdd56"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.135.tar.gz"
    source_sha256 = "3658cacaa630d90c6f1e5a9edf9ea7e09a16002a8b2d97d9e26a94cd7f42b9f5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist_0.0.135_linux_noarch_cflinuxfs3_083c4563.tgz"
    version = "0.0.135"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "3080f952364debef7187bb36178767d209c9db336acae13dff29c9cfbfcde5b5"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "2db0e48bcbd442878c1494164eb7a9b331dac301e31cea90740dc3240cc87fa3"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web_0.0.99_linux_noarch_any-stack_3080f952.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/httpd"
    sha256 = "bc45a39e03245deb9294da9f7ff9c1e884208da9a4afd79f7572c5e734610258"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.107.tar.gz"
    source_sha256 = "0ba5af4cd3f237e43c357cdf956e88242ed224367dfbaa7b588c3b7b71c635da"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd_0.0.107_linux_noarch_any-stack_bc45a39e.tgz"
    version = "0.0.107"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/nginx"
    sha256 = "2d2a28a9c530b87c73d8939482153ac83c5633937bdad7429f2de40567199e95"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.110.tar.gz"
    source_sha256 = "60ce6b175dbddd61aafa6c578dff867a5feed132548de51de9be8ed24aca7208"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx_0.0.110_linux_noarch_any-stack_2d2a28a9.tgz"
    version = "0.0.110"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-composer"
    sha256 = "7c628602c098e03f058c004cdca3cf1466031289ef5c9a19f4b2156017015fcc"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.65.tar.gz"
    source_sha256 = "cb796941ea28e4dc2ed17345a80a83d30971f968fde416b90337f29c0051ff8d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer_0.0.65_linux_noarch_any-stack_7c628602.tgz"
    version = "0.0.65"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-dist"
    sha256 = "083c4563d8acb9aaa5fb3ddfce3298f6c538c41be2eea5bc896a64960b9cdd56"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.135.tar.gz"
    source_sha256 = "0993000e63a0f2cceb0ece0bb10615f53c891d12460f4adc34b614619027bee2"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist_0.0.135_linux_noarch_cflinuxfs3_083c4563.tgz"
    version = "0.0.135"

  [[metadata.dependencies]]
    id = "paketo-buildpacks/php-web"
    sha256 = "5c126c257c6c5cc955da20d5f4113f3aaf33883b309b0bb3412d7b4f627af103"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.93.tar.gz"
    source_sha256 = "1f89ff2841593a36609f6ab88be4cc010f89d7761dc62959ab02dd021c199001"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web_0.0.93_linux_noarch_any-stack_5c126c25.tgz"
    version = "0.0.93"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/httpd"
    version = "0.0.107"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.0.110"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-dist"
    version = "0.0.135"

  [[order.group]]
    id = "org.cloudfoundry.php-compat"
    version = "0.0.57"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-composer"
    version = "0.0.65"
    optional = true

  [[order.group]]
    id = "paketo-buildpacks/php-web"
    version = "0.0.93"
