api = "0.2"

[buildpack]
  id = "org.cloudfoundry.shim.php"
  name = "PHP Shim Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/releases/download/v0.5.0/lifecycle-v0.5.0%2Blinux.x86-64.tgz"
    source_sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-compat"
    uri = "https://github.com/cloudfoundry/php-compat-cnb/releases/download/v0.0.40/php-compat-cnb-0.0.40.tgz"
    sha256 = "f3310b2acc52d0a502507ce2923fda301621a825328b6bd915b898fdaf3baa52"
    source = "https://github.com/cloudfoundry/php-compat-cnb/archive/v0.0.40.tar.gz"
    source_sha256 = "a817bc91b150160606072cbd353a5dc9936fc267741f045cef939d11dc53a83a"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    version = "0.0.40"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "9dd7669fb15fe71cb4679bc82d3bfb3c607b36eeca49d8b5fc2fe7988c5cbdbc"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.83.tar.gz"
    source_sha256 = "95b325637f334b2e2db08ebf8d99c67aad61ef80de57edbcae06ec01d5007808"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd-0.0.83-any-stack-9dd7669f.tgz"
    version = "0.0.83"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "47a189064e92ff314d0fa04701990dd8b2d868efaf3bd16fa9c18c53443ef434"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.92.tar.gz"
    source_sha256 = "ece1b02f5c350a232682c3d14dfd37a39c42d69fe3352870c08284141a027d55"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx-0.0.92-any-stack-47a18906.tgz"
    version = "0.0.92"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "b03b9fcf92428ecdbf545d70a26ffcb0138813a985711081c8fe2b70ac0aa66b"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.48.tar.gz"
    source_sha256 = "b5e0e647fe7283f31b069d31c52c1ac6d496325cf1dc71fe69b562910b32c937"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.48-any-stack-b03b9fcf.tgz"
    version = "0.0.48"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "1f484619545dd722b43125f8d352d28a337406dc9b547d4dc8bd070672096d79"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.99.tar.gz"
    source_sha256 = "76772e034aa47d8f7ae82204446ef374281cb6d612fbfbd10472c82851e81b84"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist-0.0.99-cflinuxfs3-1f484619.tgz"
    version = "0.0.99"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "c34ef34c02cea01660e0b9ae48f1d080ef5933d23e10eef80cbb406339484ce3"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.82.tar.gz"
    source_sha256 = "9b1dadbe7dbca44c1e185efebd3a535f1c861ecd43be620551103fe91b517a1d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web-0.0.82-any-stack-c34ef34c.tgz"
    version = "0.0.82"

[[order]]

  [[order.group]]
  id = "org.cloudfoundry.httpd"
  optional = true
  version = "0.0.83"

  [[order.group]]
  id = "org.cloudfoundry.php-compat"
  version = "0.0.40"

  [[order.group]]
  id = "org.cloudfoundry.php-dist"
  version = "0.0.99"

  [[order.group]]
  id = "org.cloudfoundry.php-composer"
  optional = true
  version = "0.0.48"

  [[order.group]]
  id = "org.cloudfoundry.php-web"
  version = "0.0.82"

[[order]]
  [[order.group]]
  id = "org.cloudfoundry.nginx"
  optional = true
  version = "0.0.92"

  [[order.group]]
  id = "org.cloudfoundry.php-compat"
  version = "0.0.40"

  [[order.group]]
  id = "org.cloudfoundry.php-dist"
  version = "0.0.99"

  [[order.group]]
  id = "org.cloudfoundry.php-composer"
  optional = true
  version = "0.0.48"

  [[order.group]]
  id = "org.cloudfoundry.php-web"
  version = "0.0.82"
