api = "0.2"

[buildpack]
  id = "org.cloudfoundry.shim.php"
  name = "PHP Shim Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/releases/download/v0.5.0/lifecycle-v0.5.0%2Blinux.x86-64.tgz"
    source_sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "64948313e638859359ddfa6deee45496ebf2ed671d4c49fedca22f098d088466"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "d7c34641fad008a0e0184b40016dcde4b0e1eade3206ea4f1c8fe613bcce2ea2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd_0.0.106_linux_noarch_any-stack_64948313.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "62d25e1e483b791131221e78fded7f7860642e53cf523500d8529a8961aa7c18"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.109.tar.gz"
    source_sha256 = "9ff56726dce36e96d24da80e88e7c21e26dd0d8aecf3a2cad0f9b161d8c6bcd4"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx_0.0.109_linux_noarch_any-stack_62d25e1e.tgz"
    version = "0.0.109"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-compat"
    sha256 = "f97f73e0a7f6d3e6e6827d6af34e448063e6e8ff637e4b1399d7e8f879b7b917"
    source = "https://github.com/cloudfoundry/php-compat-cnb/archive/v0.0.56.tar.gz"
    source_sha256 = "d7b642be54e3898010bdd611c5604ea1e0f0b8ff2d750d39390e8b3eda95e61b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-compat/org.cloudfoundry.php-compat_0.0.56_linux_noarch_any-stack_f97f73e0.tgz"
    version = "0.0.56"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "154237213c3d0261cb81bef216493e048167130c6a6c38698e5de0dec288c8be"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.63.tar.gz"
    source_sha256 = "fca425feb7e18c9e9bf1e894c7dbd1dea086ee84997af6465faa07b28beefab0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer_0.0.63_linux_noarch_any-stack_15423721.tgz"
    version = "0.0.63"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "083c4563d8acb9aaa5fb3ddfce3298f6c538c41be2eea5bc896a64960b9cdd56"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.135.tar.gz"
    source_sha256 = "3658cacaa630d90c6f1e5a9edf9ea7e09a16002a8b2d97d9e26a94cd7f42b9f5"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist_0.0.135_linux_noarch_cflinuxfs3_083c4563.tgz"
    version = "0.0.135"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "871768dd4344551e8a8409d4f44664b9207daf386d85db94431a4a1e12d9fc91"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.90.tar.gz"
    source_sha256 = "aec2efa4c319e70a9d268fe58a30165527f0e1100ecccd88628aa2495b21dc0b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web_0.0.90_linux_noarch_any-stack_871768dd.tgz"
    version = "0.0.90"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.106"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.109"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.135"

  [[order.group]]
    id = "org.cloudfoundry.php-compat"
    version = "0.0.56"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.63"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.90"
