api = "0.2"

[buildpack]
  id = "org.cloudfoundry.shim.php"
  name = "PHP Shim Buildpack"
  version = "{{.Version}}"

[metadata]
  dependency_deprecation_dates = []
  include_files = ["buildpack.toml"]

  [[metadata.dependencies]]
    id = "lifecycle"
    sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    source = "https://github.com/buildpack/lifecycle/releases/download/v0.5.0/lifecycle-v0.5.0%2Blinux.x86-64.tgz"
    source_sha256 = "fe37503098e964aa1a052abb50fecf2de3624c0049506e638c86dc5b4b7909e8"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3", "org.cloudfoundry.stacks.tiny"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/lifecycle/lifecycle-0.5.0-any-stack-fe375030.tgz"
    version = "0.5.0"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.httpd"
    sha256 = "9ad7ab02a99ab6706a67c2590432a4531bc795c11ba1693ee0529cd4fbc7e3d8"
    source = "https://github.com/cloudfoundry/httpd-cnb/archive/v0.0.102.tar.gz"
    source_sha256 = "4d0181b513e3f0a5e0be877cc02c717a2571726e9c58b8065e3e61dbbdd8e6d9"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.httpd/org.cloudfoundry.httpd_0.0.102_linux_noarch_any-stack_9ad7ab02.tgz"
    version = "0.0.102"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.nginx"
    sha256 = "d25a724f38f9bc40dc2ac1ab821620fb2e8ca87de1353e3f91ab5dcfc089be17"
    source = "https://github.com/cloudfoundry/nginx-cnb/archive/v0.0.106.tar.gz"
    source_sha256 = "cc147566324e2c86af5eea95efa178392d86c99c2b3bb86cfbd1a139e1bbd7e2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.nginx/org.cloudfoundry.nginx_0.0.106_linux_noarch_any-stack_d25a724f.tgz"
    version = "0.0.106"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-compat"
    sha256 = "fc43f95bddc56ef61f24b2464532d902300d994e03d7e3acfc3ae1a78c76db80"
    source = "https://github.com/cloudfoundry/php-compat-cnb/archive/v0.0.53.tar.gz"
    source_sha256 = "b9443924ab5f8174d9e11c15f27da71c2edd6bcdff441330a9f135bfb7dcbcea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-compat/org.cloudfoundry.php-compat-0.0.53-any-stack-fc43f95b.tgz"
    version = "0.0.53"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-composer"
    sha256 = "ec63e01c7fce0cec68a74ea1a797e656572949c5a4c983bfe79b1cf70ca857a7"
    source = "https://github.com/cloudfoundry/php-composer-cnb/archive/v0.0.60.tar.gz"
    source_sha256 = "3c0bec0af154a263a4e13e585e4edd77b8625c996eb472cc3f6d1dc23ade9eea"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-composer/org.cloudfoundry.php-composer-0.0.60-any-stack-ec63e01c.tgz"
    version = "0.0.60"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-dist"
    sha256 = "241d4abc0014dab176840c554c8ea8f31296f46aaa8b4f428af2fd64cd412ca9"
    source = "https://github.com/cloudfoundry/php-dist-cnb/archive/v0.0.131.tar.gz"
    source_sha256 = "86e224734cf82de20170adde35436453485db743875fdfc153acb78b69d62ffc"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-dist/org.cloudfoundry.php-dist_0.0.131_linux_noarch_cflinuxfs3_241d4abc.tgz"
    version = "0.0.131"

  [[metadata.dependencies]]
    id = "org.cloudfoundry.php-web"
    sha256 = "7c98a62e5d4852815208c4148c53c3476fb885489e7013f03dd6635854a9cefe"
    source = "https://github.com/cloudfoundry/php-web-cnb/archive/v0.0.87.tar.gz"
    source_sha256 = "92981c982bc595b30600d30598c46e56db7af821fce10b89ca769f69449b0fd2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/org.cloudfoundry.php-web/org.cloudfoundry.php-web_0.0.87_linux_noarch_any-stack_7c98a62e.tgz"
    version = "0.0.87"

[[order]]

  [[order.group]]
    id = "org.cloudfoundry.httpd"
    version = "0.0.102"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.nginx"
    version = "0.0.106"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-dist"
    version = "0.0.131"

  [[order.group]]
    id = "org.cloudfoundry.php-compat"
    version = "0.0.53"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-composer"
    version = "0.0.60"
    optional = true

  [[order.group]]
    id = "org.cloudfoundry.php-web"
    version = "0.0.87"
